MobilityData/gbfs-validator

- gbfs-validator/schema/freeBikeStatus.json
- gbfs-validator/schema/stationInformation.json
This PR adds additional numeric validation of lat/lon fields which can help find cases where lat/lon are mistakenly switched.
> Add additional numeric validation for lat/lon fields

- RULES.md
- gbfs-validator/schema/v2.1/index.js
- gbfs-validator/schema/v2.2/index.js
Hi @isabelle-dr and contributors,
thanks for the good work!
I failed to raise this during yesterdays workshop as I only noticed after the slot was finished, but in my opinion, the validator should not declare potentially valid feeds as invalid. A feed rather should be considered _invalid_ only if it clearly is not, while stating it would be valid still does not mean it could not potentially be invalid (e.g. because `free_bike_status` refers to vehicle types that are not declared).
Full disclosure: Our implementation of `vehicle_types.json` is still in progress and even though the spec says we _should_ be publishing it, we are not required to do so and yet our feeds are considered invalid ;)
> vehicle_types.json is not required

- website/src/components/Validator.vue
This PR adds the possibility to pass a `url` in the query param and start directly a validation.
This could be used to share links with partners, to share directly the result of a GBFS validation. URLs will look like: https://gbfs-validator.netlify.app/?url=https://transport.data.gouv.fr/gbfs/amiens/gbfs.json
I did not handle `options` for now, a `url` only is the most simple case.
> Start a validation when passing url query param

- website/src/components/Validator.vue
Follow up of #56. After submitting the form, update the current URL to include `?url=<url>` to make it easy to share the URL with others.
This is also a good opportunity to self document the feature added in #56
> Update URL when submitting form

- gbfs-validator/gbfs.js
- netlify.toml
Return git hash on netlify, based on COMMIT_REF env variable or package.json's version
Close #77
> Add `validatorVersion` on API responses

- gbfs-validator/versions/v1.0.js
> Do not try to validate `gbfs_versions` on v1.0

- gbfs-validator/gbfs.js
Fix #85
- A `station_id` field on vehicles in `free_bike_status.json` will not mark `vehicle_types.json` anymore as required, as the spec doesn't require it.
Code cleaning:
- `freeBikeStatusHasVehicleId` var is renamed `freeBikeStatusHasVehicleTypeId` to better reflect what it check.
https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_le/gbfs.json is not marked `invalid` anymore.
> Fix vehicle_types.json wrongly required #85

- .all-contributorsrc
- README.md
[All-contributors](https://github.com/all-contributors/all-contributors) is a specification to recognize open source contributors to a project. 
MobilityData wants to test this tool on the gbfs-validator, hopefully adding it to all other open-source projects we host (GTFS and GBFS included).
> Add All Contributors Specification

- README.md
- gbfs-validator/__test__/cli.test.js
- gbfs-validator/cli.js
- gbfs-validator/package.json
- yarn.lock
In this PR, the `cli.js` file is enhanced with additional parameters, help messages, and error handling. The following parameters were added:
```
Usage: cli [OPTIONS]...
Options:
-v, --version                    output the version number
-u, --url <feed_url>          URL of the GBFS feed
-vb, --verbose                   Verbose mode prints debugging console logs
-s, --save-report <report_path>  Local path to output report file
-pr, --print-report <yes_no>     Print report to standard output (choices: "yes", "no", default: "yes")
-h, --help                       display help for command
```
#Tasks pending before _Ready_
> feat: Enhance cli command line

- gbfs-validator/versions/schemas/v1.0/gbfs.json
- gbfs-validator/versions/schemas/v1.1/gbfs.json
- gbfs-validator/versions/schemas/v1.1/gbfs_versions.json
- gbfs-validator/versions/schemas/v2.0/gbfs.json
- gbfs-validator/versions/schemas/v2.0/gbfs_versions.json
- gbfs-validator/versions/schemas/v2.1/gbfs.json
- gbfs-validator/versions/schemas/v2.2/gbfs.json
- gbfs-validator/versions/schemas/v2.3/gbfs.json
- gbfs-validator/versions/schemas/v3.0-RC/gbfs.json
The JSON schema used for GBFS feed validation was using an invalid property. The property `required` must take an array ([reference](https://json-schema.org/understanding-json-schema/reference/object.html#required-properties)) but it was taking a boolean. 
The GBFS JSON schema was fixed in [Replace required with boolean (invalid) to array](https://github.com/MobilityData/gbfs-json-schema/pull/92). 
This PR updates the schema in [gbfs-validator](https://github.com/MobilityData/gbfs-validator).
A provider ([TIER](https://www.tier.app/en/)) is trying to update their GBFS feeds to v3.0, which is great! Unfortunately our validator is not so helpful now because it says the [feed](https://data-sharing.tier-services.io/tier_paris/gbfs/3.0) is valid although it's not. This PR will help the …
> Fix required boolean (invalid) with required array

- gbfs-validator/gbfs.js
Currently, when `manifest_url` is specified in `system_information.json`, but the file is not found at the URL, the validator fails.
Instead, the validator should inform that the `manifest.json` file is missing.
Fix https://github.com/MobilityData/gbfs-validator/issues/119
> Adds file type if `manifest.json` file is not found

- gbfs-validator/versions/schemas/v2.1/station_status.json
- gbfs-validator/versions/schemas/v2.2/station_status.json
- gbfs-validator/versions/schemas/v2.3/station_status.json
- gbfs-validator/versions/schemas/v3.0-RC/station_status.json
Fixes https://github.com/MobilityData/gbfs-validator/issues/123
Tested with this sample feed: https://data.mfdz.de/gbfs/test/gbfs.json
Before | After
-- | --
> Remove `minItems` for `vehicle_types_available`

- website/src/components/Footer.vue
Adding "maintained by MobilityData" to the footer with a link to our website, along the lines of what we have on the [GTFS Validator](https://gtfs-validator.mobilitydata.org/)
> Add "maintained by MobilityData" to the footer

- gbfs-validator/__test__/__snapshots__/gbfs.test.js.snap
- gbfs-validator/__test__/gbfs.test.js
- gbfs-validator/gbfs.js
- website/src/pages/Validator.vue
In #118 a feature to add API-Key authentication was added. 
Unfortunately some gateways require more than one key for authentication. To address this, I added a more generic approach to allow other kinds of authentication with multiple headers as well. Hence the renaming to `headers` instead of `api_key`.
I limited it to three headers, since this should be sufficient and won't overload the ui with "add header"-buttons.
> feat: add support for multiple auth headers

- gbfs-validator/versions/schemas/v2.3/free_bike_status.json
- gbfs-validator/versions/schemas/v3.0-RC/vehicle_status.json
This PR syncs the JSON Schemas after the PR https://github.com/MobilityData/gbfs-json-schema/pull/97.
It updates `available_until` regex to allow timezones.
Files are affected by this change:
`v2.3/free_bike_status.json` and `v3.0-RC/vehicle_status.json`
> Updates `available_until` regex to allow timezones

- gbfs-validator/gbfs.js
Fixes https://github.com/MobilityData/gbfs-validator/issues/142
Before | After
-- | --
Test feed for screenshots: https://api.ridecheck.app/gbfs/v3/amsterdam/gbfs.json
> Fix manifest file validation

- .github/workflows/unit_tests.yaml
- netlify.toml
- package.json
- website/package.json
- yarn.lock
The `netlify-cli` hasn't been upgraded since the 10th version. In this PR, the netlify-cli is upgraded to `15.11.0`. The intention was to upgrade it to the latest version. Unfortunately, there is a breaking change on [16.0.0](https://github.com/netlify/cli/releases/tag/v16.0.0) that prevents us from going over `16.0.0` version without changing the structure of the folders in our monorepo setup. I'm proposing to stop in `15.11.0` and address the upgrade later.  More info: https://github.com/netlify/cli/issues/5977
Fixes #134 
While upgrading the `netlify-cli`, we encountered an issue where netlify-cli dependencies were removed from the node_modules on the remote netlify builds. Locally, builds passed without problems, but not remotely. I fixed and added the nohoist behavior to the …
> chore: upgrade netlify-cli  dependency

- netlify.toml
- package.json
Netlify build broke after merging to master _mysteriously_. In this PR the yarn post-install scripts are ignored to avoid yarn crashes. This is not ideal as in the future we might add a dependency that uses the post-install pattern like netlify-cli does.
> fix: netlify build

- website/src/pages/Validator.vue
Fixes https://github.com/MobilityData/gbfs-validator/issues/150
Replaces "Authentification" (French) with "Authentication" (English).
Before | After
-- | --
> Fix authentication typo

- .github/ISSUE_TEMPLATE/new-issue-template.md
"###" markdown already applies the bold formatting so "**" is not needed.
> Remove redundant formatting in issue template

- check-systems/index.js
- gbfs-validator/cli.js
- gbfs-validator/gbfs.js
- gbfs-validator/validate.js
This PR adds code documentation in jsdoc for the following files:
- check-systems/index.js
- gbfs-validator/cli.js
- gbfs-validator/gbfs.js
- gbfs-validator/validate.js
> Code documentation in jsdoc

- gbfs-validator/gbfs.js
- website/src/components/Result.vue
Closes #127 
Modified to display `Invalid GBFS feed` if a required file is missing.
Here is the results when using [this feed](https://api.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/brest/en/gbfs.json?&key=OGNhZDNjMDQtYTA0Yi00NzU2LWE0MTItOGJlYzE1Y2E4NGEx)
> fix: Modified to display that there is an error if a required file is missing

- gbfs-validator/gbfs.js
Fixes https://github.com/MobilityData/gbfs-validator/issues/170 (follow up of https://github.com/MobilityData/gbfs-validator/issues/127)
When a file is required, but it's missing it will now show up in the error count of the file and in the summary
Before
After
Tested using this feed: https://api.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/brest/en/gbfs.json?&key=OGNhZDNjMDQtYTA0Yi00NzU2LWE0MTItOGJlYzE1Y2E4NGEx
> fix: Error count on missing required files

- .github/workflows/publish_validator.yml
- gbfs-validator/README.md
- gbfs-validator/package.json
This PR aims to fix the workflow file that would publish the package.
Logic is
If the version of the package.json doesn't match with the one published, then it will publish it. If it matches, it will stop
> Fix: publish workflow file

- gbfs-validator/__test__/__snapshots__/gbfs.test.js.snap
- gbfs-validator/__test__/gbfs.test.js
- gbfs-validator/gbfs.js
#90 
Certain feeds such as: https://mds.linkyour.city/gbfs/es_granada/gbfs.json block the default user-agent used by GOT. This PR changes the default user-agent to the format: `MobilityData GBFS-Validator/{VALIDATOR_VERSION} (NOde {NODE_VERSION})`
With the new user-agent header, this feed works
> fix: validate granada feed through new GOT user-agent

- .github/workflows/unit_tests.yaml
- gbfs-validator/README.md
- gbfs-validator/package.json
- package.json
There was an issue when installing the npm package `npm i gbfs-validator --save` after the submodule addition. I discovered from the package.json `postinstall` script will trigger when users install the package using `npm i gbfs-validator --save`. This caused an error where it would try to update the submodules when trying to download the package.
Solution
The `prepare` lifecycle script will trigger a submodule update on a local `npm install` but NOT when a user downloads the package `npm i gbfs-validator --save`. It will also trigger just before `npm publish`. This is the functionality we wanted from the beginning 
Note: I deployed version 1.0.11 locally to make sure this fix works, and it does!
> gbfs validator script fix

- .github/workflows/publish_validator.yml
As the current npm token to publish the typescript package is set to expire, the new one is set using onepassword
> update npm token for publish

- website/src/components/Result.vue
- website/src/pages/Visualization.vue
Changed error message from 
Old: "Sorry, this version is not yet implemented or not detectable !"
New: "Sorry, the validator failed to parse this file. Please check that the URL is available and points to a [gbfs.json](https://github.com/MobilityData/gbfs/blob/master/gbfs.md#gbfsjson) file. If you have any questions, please write to [sharedmobility@mobilitydata.org](mailto:sharedmobility@mobilitydata.org). Thank you
Also ran Vue linter - no functionality changed
How to test
On the validator input a non valid gbfs link ex: `https://www.mibicitubici.gob.ar/` you should see the error message
> feat: update generic error message

- website/src/pages/Home.vue
the example URL displayed in the validator form is misspelled
> Correct "exemple" URL spelling

- .github/workflows/publish_validator.yml
NODE_AUTH_TOKEN was using secret from TECHNOLOGIES vault, which is not shared externally. It's odd that it worked fine even though it couldn’t.
> fix: corrected NODE_AUTH_TOKEN
